#!/bin/bash

# SPDX-FileCopyrightText: 2017-2020 City of Espoo
#
# SPDX-License-Identifier: LGPL-2.1-or-later

set -e

cd "$( dirname "${BASH_SOURCE[0]}")"

# We want to replace this with evaka in future
if ! test -d "./keycloak/helsinki-keycloak-theme/"; then
  cd ./keycloak
  git clone https://github.com/City-of-Helsinki/helsinki-keycloak-theme.git
  cd ..
fi

docker-compose -f docker-compose.yml -f docker-compose.keycloak.yml $@
